# Generated by Django 5.0.1 on 2025-01-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bosses',
            options={'verbose_name': 'Compnay', 'verbose_name_plural': 'Companies'},
        ),
    ]
