# Generated by Django 5.0.1 on 2025-01-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='chat_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
