# Generated by Django 5.0.1 on 2025-01-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='owners',
            new_name='company',
        ),
    ]
