# Generated by Django 5.0.1 on 2025-01-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosses', '0002_alter_bosses_options'),
        ('groups', '0003_rename_owners_groups_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='company',
            field=models.ManyToManyField(related_name='companies', to='bosses.bosses'),
        ),
    ]
