# Generated by Django 5.0.1 on 2025-01-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groups_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='company',
            new_name='companies',
        ),
    ]
