# Generated by Django 5.0.1 on 2024-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='replied',
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
