# Generated by Django 5.0.1 on 2024-12-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_remove_messages_message_id_remove_messages_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_id',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
